[project]
name = "moderation-handing-service"
version = "1.0.0"
description = "Microservice for API interaction with moderation events"
authors = []
requires-python = ">=3.12"


dependencies = []